### ISSUE TITLE
In Main.java, use a ternary statement to decide what to print

### ISSUE THREAD

**Issue by Awesomeplayer165** [AadiPatangi/input-number-multiple-of-3-5#1]
Look up ternary expressions/operations if needed.

I know in swift they support it so I am assuming Java does as well

**Comment by Awesomeplayer165** [comment]
https://github.com/AadiPatangi/input-number-multiple-of-3-5/blob/995cb228ea610000534f7ab9fad8fcdb3c0b3154/Main.java#L11

In swift, we can do this:

```swift
print("The number entered is \(x.isDivisible(by: 3) && x.isDivisible(by: 5) ? "is" : "is not" ) a multiple of 3 and 5")
```

**Comment by AadiPatangi** [comment]
> Look up ternary expressions/operations if needed.
> 
> I know in swift they support it so I am assuming Java does as well

The way to do ternary statements in java makes it less efficient than the current program.

**Comment by Awesomeplayer165** [comment]
Got it. Thank you so much. I will close the issue now
